### ISSUE TITLE
[BUG] Neon OS Release 24.07.24 - wallpaper not rotating

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/neon_debos#164]
### Description

Even though gui/settings/display/wallpaper rotation  is set to 'ON' ; there is no rotation
secondly) turning that setting to OFF , backing out, then going in - setting is ON - won't hold selected OFF

### Relevant Code

gui.log from support/troubleshooting package sent to 'support' jul 24_8:57 EDT
[gui_log.txt](https://github.com/user-attachments/files/16367490/gui_log.txt)

### Other Notes

this is in my neon.yaml
```
PHAL:
  ovos-PHAL-plugin-wallpaper-manager:
    module: ovos-PHAL-plugin-wallpaper-manager
    wait_for_gui: false
    lang: en-us
    selected_provider: skill-ovos-homescreen.openvoiceos
```
