### ISSUE TITLE
[FEAT] Pre-configured WiFi option

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon_debos#96]
### Objective

Currently, wifi setup is assumed to be completed either via wifi-setup (unreliable) or via the GUI. Add an option to read network config from a file on the boot partition, similar to RaspberryOS.

### Initial Implementation Requirements

- Option to specify SSID/Password in a text file on the boot partition
- Updated documentation to note this config option
- Ensure wifi-setup service waits for this connection to be attempted

**Comment by NeonDaniel** [comment]
RPi Imager offers a method for specifying networking which generates `boot/network-.con` that looks like:
```
version: 2
wifis:
  renderer: networkd
  wlan0:
    dhcp4: true
    optional: true
    access-points:
      "TheHomeWiFi":
        password: "<hex encoded stuff>"
```
